apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongo-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MONGO_USER: "{{ .Values.mongodb.username }}"
  MONGO_PASS: "{{ .Values.mongodb.password }}"